[build]
builder = "NIXPACKS"
nixpacksPkgs = ["zlib", "libjpeg", "libpng", "freetype", "libtiff", "openjpeg", "python3", "pip", "postgresql-client"]

[deploy]
runtime = "V2"
numReplicas = 1
startCommand = "gunicorn -w 4 -b 0.0.0.0:$PORT app:app"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
